# Copyright (c) 2025 Nordic Semiconductor ASA
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause

# Configuration overlay for uicr image
# Enable UICR.SECONDARY.ENABLE
CONFIG_SOC_NRF54H20_CPURAD_ENABLE=y
CONFIG_GEN_UICR_SECONDARY=y
CONFIG_GEN_UICR_SECONDARY_PROCESSOR_RADIOCORE=y
